configs:
  - id: globalK8sClusterAnomalyDetect
    type:
      settings:
        schema: builtin:anomaly-detection.kubernetes.cluster
        scope: environment
    config:
      name: globalK8sClusterAnomalyDetect
      template: object.json
      skip: false
      parameters:
        default: false
        read:
          ###################
          ## read - readinessIssues
          ## Fields:
          ## enabled - enabled
          ## sampleMin - samplePeriodInMinutes
          ## obsMin - observationPeriodInMinutes
          ##############
          type: value
          value:
            enabled: true
            sampleMin: 3
            obsMin: 5
        cpu:
          ###################
          ## cpu - cpuRequestsSaturation
          ## Fields:
          ## enabled - enabled
          ## thresh - threshold
          ## sampleMin - samplePeriodInMinutes
          ## obsMin - observationPeriodInMinutes
          ##############
          type: value
          value:
            enabled: true
            sampleMin: 3
            obsMin: 5
            thresh: 90
        mem:
          ###################
          ## mem - memoryRequestsSaturation
          ## Fields:
          ## enabled - enabled
          ## thresh - threshold
          ## sampleMin - samplePeriodInMinutes
          ## obsMin - observationPeriodInMinutes
          ##############
          type: value
          value:
            enabled: true
            sampleMin: 8
            obsMin: 10
            thresh: 95
        pod:
          ###################
          ## pod - podsSaturation
          ## Fields:
          ## enabled - enabled
          ## thresh - threshold
          ## sampleMin - samplePeriodInMinutes
          ## obsMin - observationPeriodInMinutes
          ##############
          type: value
          value:
            enabled: false
            sampleMin: 3
            obsMin: 5
            thresh: 90
        mon:
          ###################
          ## mon - monitoringIssues
          ## Fields:
          ## enabled - enabled
          ## sampleMin - samplePeriodInMinutes
          ## obsMin - observationPeriodInMinutes
          ##############
          type: value
          value:
            enabled: true
            sampleMin: 3
            obsMin: 5