configs:
  # srg
  - id: srg-opr-excel-$RELEASE_PRODUCT
    type:
      settings:
        schema: app:dynatrace.site.reliability.guardian:guardians
        schemaVersion: 1.1.2
        scope: environment
    config:
      skip: true
      name: "Six Pillars - Operational Excellence - $RELEASE_PRODUCT"

      template: srg-opr-excel.json
      
      parameters:
        tags:
          type: list
          values:
            - "usecase:sixpillars"
        releaseProduct:
          type: environment
          name: RELEASE_PRODUCT        
        # objective - apdex - slo
        reference_slo_apdex: ["slo", "slo-apdex-$RELEASE_PRODUCT", "name"]
        reference_slo_metric_apdex:
          type: compound
          format: "func:slo.{{ .reference_slo_apdex }}"
          references:
            - reference_slo_apdex
        target_slo_apdex: 95
        warning_slo_apdex: 97

  # application-web 
  - id: app-$RELEASE_PRODUCT
    type:
      api: application-web
    config:
      skip: true
      template: application.json
      name:
        type: compound
        format: "{{ .releaseProduct }}-{{ .releaseStage }}-{{ .useCase }}"
        references:
          - releaseProduct
          - releaseStage
          - useCase
      parameters:  
        releaseProduct:
          type: environment
          name: RELEASE_PRODUCT
        releaseStage:
          type: environment
          name: RELEASE_STAGE
        useCase:
          type: environment
          name: USE_CASE
          
  #slo
  - id: slo-apdex-$RELEASE_PRODUCT
    type:
      api: slo
    config:
      skip: true
      template: slo-apdex.json
      name:
        type: compound
        format: "{{ .releaseProduct }}_{{ .releaseStage }}_slo_apdex_{{ .useCase }}"
        references:
          - releaseProduct
          - releaseStage
          - useCase
      parameters:
        metric_name: 
          type: compound
          format: "{{ .releaseProduct }}_{{ .releaseStage }}_slo_apdex_{{ .useCase }}"
          references:
            - releaseProduct
            - releaseStage
            - useCase
        application_name: ["application-web", "app-$RELEASE_PRODUCT", "name"]
        target_apdex: 95
        warning_apdex: 97
        useCase:
          type: environment
          name: USE_CASE
        releaseStage:
          type: environment
          name: RELEASE_STAGE
        releaseProduct:
          type: environment
          name: RELEASE_PRODUCT
        evaluationWindow:
          type: environment
          name: EVALUATION_WINDOW
          default: "-1h"

  # app-detection-rule 
  - id: appDetection-$RELEASE_PRODUCT
    type:
      settings:
        schema: builtin:rum.web.app-detection
        scope: environment
        schemaVersion: "2.0.1"
    config:
      skip: true
      name: 
        type: compound
        format: "{{ .releaseProduct }}-{{ .releaseStage }}-{{ .useCase }}"
        references:
          - releaseProduct
          - releaseStage
          - useCase
      template: application-detection-rule.json
      parameters:
        applicationId: ["application-web", "app-$RELEASE_PRODUCT", "id"]
        domain_url:
          type: environment
          name: DOMAIN_URL
        releaseProduct:
          type: environment
          name: RELEASE_PRODUCT
        useCase:
          type: environment
          name: USE_CASE

  - id: clickpath-synth-monitor-$RELEASE_PRODUCT
    type:
      api: synthetic-monitor
    config:
      skip: true
      name:
        type: compound
        format: "{{ .releaseProduct }}-{{ .releaseStage }}-clickpath-{{ .useCase }}"
        references:
          - releaseProduct
          - releaseStage
          - useCase
      template: synthetic-clickpath.json   
      parameters:
        description: Clickpath for simplenode     
        applicationId: ["application-web", "app-$RELEASE_PRODUCT", "id"]
        locations:
          type: list
          values:
            - SYNTHETIC_LOCATION-000000000000000F # North Virginia Public synthetic location ID on AWS
        frequencyMin: 5
        url:
          type: environment
          name: DOMAIN_URL
        releaseProduct:
          type: environment
          name: RELEASE_PRODUCT
        releaseStage:
          type: environment
          name: RELEASE_STAGE
        useCase: 
          type: environment
          name: USE_CASE


