configs:
  - id: config-acl-none
    config:
      name: Private connection
      template: config.json
    type:
      settings:
        schema: app:dynatrace.github.connector:connection
        schemaVersion: "1.0.1"
        scope: environment
        permissions:
          allUsers: none
